config/routes.rb
Grappes::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root :to => "travels#index"

  resources :travels do
    collection { post :import }
  end

  

end

app/models/travel.rb
require 'action_view'
include ActionView::Helpers::DateHelper
include Geocoder::Model::Mongoid

class Travel
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Mongoid::Attributes::Dynamic

  field :start_city, type: String
  field :end_city, type: String
  field :end_country, type: String
  field :price, type: Float
  field :places_available, type: Integer
  field :about, type: String
  field :departure, type: DateTime
  field :arrival, type: DateTime
  field :stopover, type: Integer
  field :company, type: String
  field :lowcost, type: Mongoid::Boolean
  field :type, type: String
  field :start_airport, type: String
  field :start_airport_code, type: String
  field :end_airport_code, type: String
  field :end_airport, type: String
  field :coordinates, :type => Array
  field :title, :type => String
  field :prefered, :type => Mongoid::Boolean
  field :direct_trip, :type => Mongoid::Boolean
  #Automatic fields
  field :start_time, type: Float
  field :end_time, type: Float
  field :duration, type: Integer
  field :search_date, type: DateTime

  geocoded_by :end_city               # can also be an IP address

  # MongoDB Associations
  has_many :moods

  # Image upload with Paperclip & Mongoid
  has_mongoid_attached_file :image,
    :styles => {
      :original => ['1920x1680>', :jpg],
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250',    :jpg],
      :large    => ['500x500>',   :jpg]
    }
  do_not_validate_attachment_file_type :image

  before_validation :set_duration
  before_validation :set_start_time
  before_validation :set_end_time
  before_validation :set_default_stopover
  after_validation :geocode          # auto-fetch coordinates

  # We use several scopes to filter in the model

  # We want to only return the travels between a range of price
  scope :in_budget, lambda { |start_price, end_price|
    where(:price => {'$gte' => start_price.to_f, '$lte' => end_price.to_f})
  }

  # Only return the travel between a date range
  scope :with_start_date, lambda { |start_date|
    start_date_s = start_date.to_date.beginning_of_day
    start_date_e = start_date.to_date.end_of_day

    where(:departure => {'$gte' => start_date_s, '$lte' => start_date_e})
  }

  scope :with_end_date, lambda { |end_date|
    end_date_s =  end_date.to_date.beginning_of_day
    end_date_e =  end_date.to_date.end_of_day

    where(:arrival => {'$gte' => end_date_s, '$lte' => end_date_e})
  }

  scope :with_people, lambda { |number_of_people|
    where(:places_available => {'$gte' => number_of_people.to_i})
  }

  scope :from_airport, lambda { |iata_code|
    airport = Airport.where(iata_code: iata_code).first
    if(airport['name'] == 'All Airports')
      where(start_city: airport['city'])
    else
      where(start_airport_code: iata_code)
    end
  }

  scope :from, lambda { |city|
    where(start_city: city)
  }


  scope :prefered, lambda { |test|
    where(:prefered => true)
  }

  scope :within_duration, lambda { |min_duration, max_duration|
    where(:duration => {'$gte' => min_duration.to_i, '$lte' => max_duration.to_i})
  }

  scope :within_start_time, lambda { |start_time_min, start_time_max|
    where(:start_time => {'$gte' => start_time_min.to_f, '$lte' => start_time_max.to_f})
  }

  scope :within_end_time, lambda { |end_time_min, end_time_max|
    where(:end_time => {'$gte' => end_time_min, '$lte' => end_time_max})
  }

  scope :number_of_stopover, lambda { |nb_of_stopover|
    where(:stopover => {:$lte => nb_of_stopover.to_i})
  }

  scope :not_in_countries, lambda { |countries|
    not_in(:end_country => countries)
  }

  scope :not_in_companies, lambda { |companies|
    not_in(:company => companies)
  }

  scope :with_mood, lambda { |m_id|
    mood = Mood.find(m_id.to_s)

    Travel.where(:moods.in => [mood.id])
  }

  # Import method
  def self.import(file)
    SmarterCSV.process(file.path) do |array|
      # we're passing a block in, to process each resulting hash / =row (the block takes array of hashes)
      # when chunking is not enabled, there is only one hash in each array
      Travel.create( array.first )
    end
  end

  # The duration of a trip is the time difference between arrival and departure
  def set_duration
    self.duration = rand(0..12) if self.duration.nil?
  end

  private

  def set_default_stopover
    self.stopover = 0 if self.stopover.nil?
  end

  def set_start_time
    self.start_time = self.departure.strftime("%H.%M").to_f unless self.start_time.nil?
  end

  def set_end_time
    self.end_time = self.arrival.strftime("%H.%M").to_f unless self.end_time.nil?
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :edit, :update, :destroy]

  # GET /travels
  def index
    store_search_params_in_cache(params)
    #retrieve_search_params_from_cookies

    #TODO : do a method for min and max
    @max_price = params[:max_price] || 600 #Travel.pluck(:price).max || 500
    @min_duration = 0  # Travel.pluck(:duration).min || 0
    @max_duration = 24 # Travel.pluck(:duration).max || 12

    @minmax_hour = [0,24] #Travel.pluck(:departure).map{ |e| e.hour}.minmax
    @front_travels = Travel.prefered("ok").empty? ? Travel.all : Travel.prefered("ok")
    @moods = Mood.all.uniq

    @cms = Cms.where(:language == "fr").first

    @citys = []
    @coordinates = {}
    @citys = Airport.where(first_class: true).map {|t|
      @coordinates[t.city] = {lat:t.latitude,lng:t.longitude}
      hash = {}
      hash["value"]       = t.city
      hash["label"]       = "#{t.city} - #{t.iata_code}"

      hash
    }.uniq
    #Qpx::Api.logger.debug "========= Cities = #{@citys.inspect}"
    # Nothing to do until user selected params.
    unless params[:from].present? and params[:min_date].present? and params[:max_date].present?
      Rails.logger.warn "No search to do. Insufficient params: #{params}"
      return
    end

    @travels = params.size == 2 ? nil : Travel.in_budget(0, @max_price)
    puts "=== Params: #{params}"
    puts "=== Initial travels count: "+ @travels.count.to_s
    #TODO: do a method for search
    filter_travel_general_info(params)

    puts "=== General travels count: "+ @travels.count.to_s
    #TODO: do a method for search
    ########## QPX: call api and refilter, unless there is travels filtered. ###########
    #TODO: call API even when Travels are outdated (use the search_date field).
    if @travels.blank? and params[:from].present?
      start_date  = params[:min_date].to_time if params['min_date'].present?
      end_date    = params[:max_date].to_time if params['max_date'].present?
      nb_people   = (params[:nb_people].present?)?params[:nb_people].to_i : 1
      Qpx::Api.multi_search_trips_by_city(params[:from],start_date,end_date,nb_people,@max_price)
      @travels = Travel.in_budget(0, @max_price)
      filter_travel_general_info(params)
      puts "=== After Api Call travels count: "+ @travels.count.to_s
      #TODO: do a method for search
      filter_travel_details(params)
      puts "=== After details filters travels count: "+ @travels.count.to_s
      #TODO: do a method for search
    end
    ########## END QPX ###########

    @stopover = @travels.pluck(:stopover).uniq.sort_by!{ |e| e } if @travels
    @companies = @travels.pluck(:company).uniq if @travels
    @end_countries = @travels.pluck(:end_country).uniq.sort_by!{ |e| e.downcase }.delete_if(&:empty?) if @travels

  end

  def filter_travel_general_info(params)
    @travels = @travels.from(params[:from]) if params[:from].present?
    @travels = @travels.in_budget(params[:min_budget], params[:max_budget]) if (params[:min_budget].present? && params[:max_budget].present?)
    @travels = @travels.with_start_date(params[:min_date]) if params[:min_date].present?
    @travels = @travels.with_end_date(params[:max_date]) if params[:max_date].present?
    @travels = @travels.with_people(params[:nb_people]) if params[:nb_people].present?
  end


  def filter_travel_details(params)
    @travels = @travels.within_duration(params[:min_travel_time], params[:max_travel_time]) if params[:min_travel_time].present?
    @travels = @travels.number_of_stopover(params[:stopover]) if params[:stopover].present?
    #between start time and end_time
    @travels = @travels.within_start_time(params[:min_start_time], params[:max_start_time]) if params[:min_start_time].present?
    @travels = @travels.within_end_time(params[:min_end_time], params[:max_end_time]) if params[:min_end_time].present?
    @travels = @travels.order_by(:price => :asc).limit(50) if @travels
    @travels = @travels.not_in_countries(params[:countries]) if params[:countries].present?
    @travels = @travels.not_in_companies(params[:companies]) if params[:companies].present?
    @travels = @travels.with_mood(params[:mood]) if params[:mood].present?
    # we want to show the cheapest flights first
    @travels.asc(:price) if @travels
  end

  # GET /travels/1
  def show
  end

  # GET /travels/new
  def new
    @travel = Travel.new
  end

  # GET /travels/1/edit
  def edit
  end

  # POST /travels
  def create
    @travel = Travel.new(travel_params)

    if @travel.save
      redirect_to @travel, notice: 'Travel was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /travels/1
  def update
    if @travel.update(travel_params)
      redirect_to @travel, notice: 'Travel was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /travels/1
  def destroy
    @travel.destroy
    redirect_to travels_url, notice: 'Travel was successfully destroyed.'
  end

  def import
    Travel.import(params[:file])
    redirect_to '/admin/travel', notice: "Travels imported."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_travel
    @travel = Travel.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def travel_params
    params.require(:travel).permit(:start_city, :end_city, :price, :places_available, :about, :departure_time, :arrival_time, :direct_trip, :company, :lowcost, :type, :start_airport, :end_airport)
  end

  def store_search_params_in_cache(params)
    cookies[:from] = { :value => params[:from], :expires => Time.now + 2592000} if params[:from].present?

    cookies[:min_budget] = { :value => params[:min_budget], :expires => Time.now + 2592000} if params[:min_budget].present?
    cookies[:max_budget] = { :value => params[:max_budget], :expires => Time.now + 2592000} if params[:max_budget].present?

    cookies[:min_date] = { :value => params[:min_date], :expires => Time.now + 2592000} if params[:min_date].present?
    cookies[:max_date] = { :value => params[:max_date], :expires => Time.now + 2592000} if params[:max_date].present?
  end

  def retrieve_search_params_from_cookies
    if !cookies[:min_date].blank?
      if cookies[:min_date].to_date >= Date.today
        params[:from] = cookies[:from] if cookies[:from]
        params[:min_budget] = cookies[:min_budget] unless cookies[:min_budget].blank?
        params[:max_budget] = cookies[:max_budget] unless cookies[:max_budget].blank?
        params[:min_date] = cookies[:min_date] unless cookies[:min_date].blank?
        params[:max_date] = cookies[:max_date] unless cookies[:max_date].blank?
      end
    end
  end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_form.html.erb
<%= form_for(@travel) do |f| %>
  <% if @travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
      <% @travel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_city %><br>
    <%= f.text_field :start_city %>
  </div>
  <div class="field">
    <%= f.label :end_city %><br>
    <%= f.text_field :end_city %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :places_available %><br>
    <%= f.number_field :places_available %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :departure %><br>
    <%= f.datetime_select :departure %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br>
    <%= f.datetime_select :arrival %>
  </div>
  <div class="field">
    <%= f.label :direct_trip %><br>
    <%= f.check_box :direct_trip %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :lowcost %><br>
    <%= f.check_box :lowcost %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :start_airport %><br>
    <%= f.text_field :start_airport %>
  </div>
  <div class="field">
    <%= f.label :end_airport %><br>
    <%= f.text_field :end_airport %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/travels/edit.html.erb
<h1>Editing travel</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>

app/views/travels/index.html.erb
<a href="#" id="left_button" data-direction="left"></a>
<a href="#" id="right_button" data-direction="right"></a>
<div id="sidebar_left">
  <h2><%= @cms.title_sidebar_left %></h2>
  <div id="accordion">
    <h3 class="length"><%= @cms.travel_length %></h3>
    <div class="travel_time" data-min="<%= @min_duration %>" data-max="<%= @min_duration %>">
      <span class="left_shadow"></span>
      <%= form_tag '', :method => :get do %>
            <%= hidden_field_tag :min_travel_time, params[:min_travel_time] %>
            <%= hidden_field_tag :max_travel_time, params[:max_travel_time] %>
          <div class="range_with_tooltip" id="slider-range-travel"></div>
      <% end %>
    </div>
    <h3 class="horaires"><%= @cms.within_time %></h3>
    <div class="within_time" data-minhour="<%= @minmax_hour[0] %>" data-maxhour="<%= @minmax_hour[1] %>">
      <span class="left_shadow"></span>
      <span class="start">
        <%= form_tag '', :method => :get do %>
            <%= hidden_field_tag :min_start_time, params[:min_start_time] %>
            <%= hidden_field_tag :max_start_time, params[:max_start_time] %>
          <div class="range_with_tooltip" id="slider-range-start"></div>
      <% end %>
      </span>
      <span class="end">
        <%= form_tag '', :method => :get do %>
            <%= hidden_field_tag :min_end_time, params[:min_end_time] %>
            <%= hidden_field_tag :max_end_time, params[:max_end_time] %>
          <div class="range_with_tooltip" id="slider-range-end"></div>
      <% end %>
      </span>
    </div>
    <h3 class="stopover"><%= @cms.stopover %></h3>
    <div>
      <span class="left_shadow"></span>
      <%= form_tag('', :method => :get, class: "stopover_form") do %>
        <% @stopover.try(:each) do |stopover| %>
              <p><%= radio_button_tag :stopover, stopover %> <label for="stopover_<%= stopover %>"><%= stopover_text(stopover) %></label></p>
        <% end %>
      <% end %>
    </div>
    <h3 class="companies"><%= @cms.excluded_companies %></h3>
    <div>
      <span class="left_shadow"></span>
      <%= form_tag('', :method => :get, class: "companies") do %>
          <% @companies.try(:each_with_index) do |company, index| %>
              <p>
                <%= check_box_tag "companies[]", company, nil, :id => "company_#{company}" %>
                <label for="company_<%= company %>"><%= company%></label>
              </p>
          <% end %>
      <% end %>
    </div>
    <h3 class="country"><%= @cms.excluded_countries %></h3>
    <div>
      <span class="left_shadow"></span>
      <%= form_tag('', :method => :get, class: 'no_s exclude') do %>
          <% @end_countries.try(:each_with_index) do |country, index| %>
          <p><%= check_box_tag "countries[]", country, nil, :id => "country_#{country}" %> <label for="country_<%= country %>"><%= country %></label></p>
          <% end %>
      <% end %>
    </div>
    <h3 class="mood"><%= @cms.moods %></h3>
    <div>
      <span class="left_shadow"></span>
      <%= form_tag('', :method => :get) do %>
          <% @moods.each_with_index do |mood, index| %>
              <p><%= radio_button_tag :mood, mood.id %> <label for="mood_<%= mood.id %>"><%= image_tag mood.icon.url(:normal) %></label></p>
          <% end %>
      <% end %>
    </div>
  </div>
  <a href="#" id="reset_filter"><%= image_tag('filter_reset.png') %><%= @cms.reset_fields %></a>
  <span class="loading hidden radio_button"></span>
</div>
<div id="sidebar_right">
  <div class="shadow_right"></div>
  <div id="loader">
      <ul id="travel_list" data-cities="<%= @citys.compact.to_json %>" data-coordinates="<%= @coordinates.to_json %>">
        <% @travels.try(:each_with_index) do |travel, i| %>
          <% unless travel.coordinates.blank? %>
          <li data-color="color<%= i %>" data-coordinates="<%= travel.coordinates %>" data-company="<%= travel.company %>" data-content="<%= travel.about %>" data-starttime="<%= travel.departure.strftime('%H.%M') %>" data-endtime="<%= travel.arrival.strftime('%H.%M') %>" data-imageurl="<%= travel.image(:medium) %>">
            <div>
                <h3 class="city" data-endcity="<%= travel.end_city %>" data-endairport="<%= travel.end_airport_code %>" data-startcity="<%= travel.start_city %>" data-startairport="<%= travel.start_airport_code %>"><%= travel.end_city %> <span>(<%= travel.end_airport_code %>)</span></h3>
                <span class="price"><%= @cms.from_price1 %>><br/><%= @cms.two_way_trip %>
                    <span><%= number_to_currency(travel.price, locale: :fr, precision: 0, format: "%n%u") %></span>
                </span>
              <div class="start"><%= long_date_with_html(travel.departure) %><br/><%= travel.departure.strftime("%H") %>h<%= travel.departure.strftime("%M") %></div>
              <div class="end"><%= long_date_with_html(travel.arrival) %><br/><%= travel.arrival.strftime("%H") %>h<%= travel.arrival.strftime("%M") %></div>
            </div>
            <a class="open_pin" href="#"><%= @cms.more %></a>
          </li>
        <% end %>
        <% end %>
      </ul>
  </div>
</div>
<div class="span3">
  <div class="span8">
    <div class="panel panel-default">
      <div id="map"></div>
      <div class="wrapper">
        <div class="bloc first fo">
          <%= image_tag("grapy_logo_bloc.png") %>
          <p><%= raw @cms.first_block_test %></p>
          <h5 class="tag_line"><%= raw @cms.tag_line %>
          </h5>
          <a class="tag_click" href="#"><%= image_tag('go_blanc.jpg') %></a>
        </div>
        <% unless @front_travels.nil? or @front_travels.empty? %>
        <div class="bloc">
          <h4><%= @front_travels[0].end_city %><span> (<%= @front_travels[0].end_airport_code %>)</span></h4>
          <div>
            <div class="blurred">
              <%= image_tag('ad1.png') %>
              <span></span>
            </div>
            <h5><%= @front_travels[0].title %></h5>
            <p><%= @front_travels[0].about %></p>
            <p class="end_bloc"><%= @cms.from_price2 %> <%= number_to_currency(@front_travels[0].price, locale: :fr, precision: 0, format: "%n%u") %> <a href="#"><%= image_tag("go_jaune.png") %></a> </p>
          </div>
        </div>
        <div class="bloc ln">
          <%= image_tag('ad1.png') %>
        </div>

        <div class="bloc fo">
          <h4><%= @front_travels[0].end_city %><span> (<%= @front_travels[0].end_airport_code %>)</span></h4>
          <div>
            <div class="blurred">
              <%= image_tag('ad1.png') %>
              <span></span>
            </div>
            <h5><%= @front_travels[0].title %></h5>
            <p><%= @front_travels[0].about %></p>
            <p class="end_bloc"><%= @cms.from_price2 %> <%= number_to_currency(@front_travels[0].price, locale: :fr, precision: 0, format: "%n%u") %> <a href="#"><%= image_tag("go_jaune.png") %></a> </p>
          </div>
        </div>
        <div class="bloc">
          <h4><%= @front_travels[0].end_city %><span> (<%= @front_travels[0].end_airport_code %>)</span></h4>
          <div>
            <div class="blurred">
              <%= image_tag('ad1.png') %>
              <span></span>
            </div>
            <h5><%= @front_travels[0].title %></h5>
            <p><%= @front_travels[0].about %></p>
            <p class="end_bloc"><%= @cms.from_price2 %> <%= number_to_currency(@front_travels[0].price, locale: :fr, precision: 0, format: "%n%u") %> <a href="#"><%= image_tag("go_jaune.png") %><b/a> </p>
          </div>
        </div>
      <% end %>
        <div class="bloc ln">
          <%= image_tag('ad2.png') %>
        </div>

      </div>
      </div>
  </div>
</div>
<div id="travel_loading_gif"><%= image_tag('travel_loading.gif') %> <br/>Chargement... </div>
<% content_for(:more_js) do %>
    <script type="text/javascript">
        travelsJs.init();
        travelsJs.geoMap();
    </script>
<% end %>

app/views/travels/new.html.erb
<h1>New travel</h1>

<%= render 'form' %>

<%= link_to 'Back', travels_path %>

app/views/travels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start city:</strong>
  <%= @travel.start_city %>
</p>

<p>
  <strong>End city:</strong>
  <%= @travel.end_city %>
</p>

<p>
  <strong>Price:</strong>
  <%= @travel.price %>
</p>

<p>
  <strong>Places available:</strong>
  <%= @travel.places_available %>
</p>

<p>
  <strong>About:</strong>
  <%= @travel.about %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @travel.departure %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @travel.arrival %>
</p>

<p>
  <strong>Direct trip:</strong>
  <%= @travel.direct_trip %>
</p>

<p>
  <strong>Company:</strong>
  <%= @travel.company %>
</p>

<p>
  <strong>Lowcost:</strong>
  <%= @travel.lowcost %>
</p>

<p>
  <strong>Type:</strong>
  <%= @travel.type %>
</p>

<p>
  <strong>Start airport:</strong>
  <%= @travel.start_airport %>
</p>

<p>
  <strong>End airport:</strong>
  <%= @travel.end_airport %>
</p>

<%= link_to 'Edit', edit_travel_path(@travel) %> |
<%= link_to 'Back', travels_path %>